ENV_DATA:
  radosnamespace_name: "ocs-storagecluster-cephblockpool-consumer-bm5-c03"
  subvolumegroup_name: "consumer-bm5-c03"
  provider_cluster_name: "ibm-bm-p5"
  cluster_namespace: "openshift-storage-client"
