ENV_DATA:
  radosnamespace_name: "ocs-storagecluster-cephblockpool-consumer-bm3-c03"
  subvolumegroup_name: "consumer-bm3-c03"
  provider_cluster_name: "ibm-bm-p3"
  cluster_namespace: "openshift-storage-client"
