apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: brew-registry
spec:
  imageDigestMirrors:
  - mirrors:
    - brew.registry.redhat.io
    source: registry.redhat.io
  - mirrors:
    - brew.registry.redhat.io/rhacm2
    source: registry.redhat.io/rhacm2
  - mirrors:
    - brew.registry.redhat.io
    source: registry.stage.redhat.io
  - mirrors:
    - brew.registry.redhat.io
    source: registry-proxy.engineering.redhat.com
  - source: registry.redhat.io/rhacm2/submariner-operator-bundle
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/submariner-bundle-0-22
  - source: registry.redhat.io/rhacm2/submariner-gateway-rhel9
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/submariner-gateway-0-22
  - source: registry.redhat.io/rhacm2/submariner-rhel9-operator
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/submariner-operator-0-22
  - source: registry.redhat.io/rhacm2/submariner-route-agent-rhel9
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/submariner-route-agent-0-22
  - source: registry.redhat.io/rhacm2/submariner-globalnet-rhel9
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/submariner-globalnet-0-22
  - source: registry.redhat.io/rhacm2/lighthouse-agent-rhel9
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/lighthouse-agent-0-22
  - source: registry.redhat.io/rhacm2/lighthouse-coredns-rhel9
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/lighthouse-coredns-0-22
  - source: registry.redhat.io/rhacm2/nettest-rhel9
    mirrors:
    - quay.io/redhat-user-workloads/submariner-tenant/nettest-0-22
